---
page_title: "cloudpilotai_cluster_setting Resource - terraform-provider-cloudpilotai"
subcategory: ""
description: |-
  Manages CloudPilot AI cluster-level settings for an existing cluster.
---

# cloudpilotai_cluster_setting

Manages CloudPilot AI cluster-level settings exposed by `/api/v1/clusters/{cluster_id}/setting`.

## Example Usage

```terraform
resource "cloudpilotai_cluster_setting" "this" {
  cluster_id           = cloudpilotai_eks_cluster.this.cluster_id
  enable_node_repair   = true
  enable_disk_monitor  = true
  maintenance_enabled  = false
  discount             = 0.15
  pre_run_command      = "echo pre"
  post_run_command     = "echo post"
}
```

<!-- schema generated by tfplugindocs -->
